### ISSUE TITLE
Could not find package GapAfzar/gap-sdp-api at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

### ISSUE THREAD

**Issue by mrmrn** [GapAfzar/Gap-SDP-API#1]
hi,
dear delopers,
thank you for the package.
I am trying to install this package but it gave to me:
`Could not find package GapAfzar/gap-sdp-api at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability`
I tried to use @dev branch if exist but it gave me the same error.
I am using laravel 5.4. How can I use this package?

**Comment by mrmrn** [comment]
آقا من نمیدونم این ایراد برطرف شده یا خیر. منتهی من دستی اضافه کردم کلاس رو تو لاراول و داره کار میکنه.

**Comment by webineh** [comment]
برای من هم مشکل داره . دستی راه حل درستی نیست . من سعی میکنم یه نسخه لاراولی بر پایه 
SDP
اصلی بنویسم

**Comment by saber13812002** [comment]
داداشا

کافیه نسخه رو بزنید master

همون نسخه که در packagist ارائه شده

یا مسیری که من گفتم اینجا رو برید

https://github.com/saber13812002/Gap-SDP-API
