### ISSUE TITLE
force cb_data

### ISSUE THREAD

**Issue by mahdizojaji** [GapAfzar/Gap-SDP-API#16]
طبق داکیومنت در لینک زیر:
https://developer.gap.im/doc/botplatform#inline_keyboard-description

گفته شده که تنظیم 
cb_data
 اجباری نیست

و میشه فقط 
text 
برای اینلاین کیبورد در نظر گرفت ولی در صورتی که فقط 
text 
تنظیم بشه 
این ارور رو برمیگردونه:
`{'error': 'Invalid data passed: inline_keyboard'}`

**Comment by ehsansabet** [comment]
InlineKeyboard has 3 type:

1. Required: **text, cb_data**
2. Required: **text, url**. Optional: **open_in**
3. Required: **text, amount, currency, ref_id**. Optional: **desc**

Documents:
https://my.gap.im/doc/botplatform
